"""
Applying ``sql/schema.sql``, and creating the staging table the upsert needs.

Both statements are idempotent -- ``CREATE TABLE IF NOT EXISTS``, ``CREATE
INDEX IF NOT EXISTS`` -- so running this against a database that is already
set up is a no-op rather than an error. That is deliberate: the writer calls it
before every run, and a first run on a fresh container should not need a
separate remembered step.

What it is NOT is a migration framework. There is no version table and no
down-grade. Adding a column to sql/schema.sql will not alter a table that
already exists, and this file will not pretend otherwise -- it will silently do
nothing, which is the honest behaviour for ``IF NOT EXISTS`` and the reason
``recreate()`` exists for development.
"""

from pathlib import Path

from src.db import contract
from src.db.settings import Database

SCHEMA = Path("sql/schema.sql")

# Where Spark bulk-loads before the merge. Named after its destination so the
# pairing is obvious in a table listing.
STAGING = f"staging_{contract.TABLE}"

# UNLOGGED because the contents survive exactly one statement: the merge reads
# it and the next run truncates it. Skipping the write-ahead log makes the bulk
# load materially faster and costs only crash-durability of data that is
# regenerated by re-running anyway.
#
# Not TEMP, which is what a first guess reaches for. A temporary table belongs
# to one session, and Spark's JDBC writer opens its own connection per
# partition -- so a TEMP staging table would be created on one connection and
# invisible to every writer, producing "relation does not exist" from a table
# you just made.
#
# LIKE keeps the column types in one place. INCLUDING DEFAULTS so cleaned_at's
# NOT NULL is satisfiable without the writer sending a value for it; the merge
# does not read it from here in any case.
STAGING_DDL = (
    f"CREATE UNLOGGED TABLE IF NOT EXISTS {STAGING} "
    f"(LIKE {contract.TABLE} INCLUDING DEFAULTS)"
)


def _connect(database: Database):
    """
    :param database: Where to connect.
    :returns: An open psycopg2 connection.
    :raises RuntimeError: If psycopg2 is not installed, saying so plainly --
        the driver error names a module and not what needed it.
    """
    try:
        import psycopg2
    except ImportError as exc:  # pragma: no cover - environment failure
        raise RuntimeError(
            "psycopg2 is required to run migrations and the upsert. "
            "pip install -r requirements.txt"
        ) from exc

    return psycopg2.connect(database.dsn)


def migrate(database: Database, schema: Path = SCHEMA) -> None:
    """
    Creates the table, its indexes and the staging table if they are absent.

    :param database: Where to apply it.
    :param schema: The DDL file.
    :raises FileNotFoundError: If the schema file is missing, which is a
        broken checkout rather than a database problem.
    """
    if not schema.exists():
        raise FileNotFoundError(f"schema not found: {schema.resolve()}")

    with _connect(database) as connection:
        with connection.cursor() as cursor:
            cursor.execute(schema.read_text(encoding="utf-8"))
            cursor.execute(STAGING_DDL)


def truncate_staging(database: Database) -> None:
    """
    Empties the staging table so a load cannot inherit the previous run's rows.

    Called before every load rather than after, on the principle that cleanup
    which only happens on the success path does not happen. A run that dies
    mid-write leaves rows here; the next run's truncate is what removes them.

    :param database: Where the staging table lives.
    """
    with _connect(database) as connection:
        with connection.cursor() as cursor:
            cursor.execute(f"TRUNCATE {STAGING}")


def merge(database: Database) -> int:
    """
    Runs the upsert that moves the staged batch into the live table.

    One statement, one transaction: the run lands completely or not at all.
    There is no partial state for a caller to reason about, which is what makes
    a failed run safe to simply re-run.

    :param database: Where both tables live.
    :returns: Rows inserted or updated.
    """
    statement = contract.merge_statement(STAGING)
    with _connect(database) as connection:
        with connection.cursor() as cursor:
            cursor.execute(statement)
            return cursor.rowcount


def recreate(database: Database) -> None:
    """
    Drops both tables and rebuilds them from the schema file.

    The development escape hatch, and the answer to what ``migrate`` will not
    do: a column added to sql/schema.sql reaches an existing database only this
    way. Destructive by definition, so it is never called by the writer -- it
    is here to be called deliberately, by ``make db-reset``.

    :param database: Where to do it.
    """
    with _connect(database) as connection:
        with connection.cursor() as cursor:
            cursor.execute(f"DROP TABLE IF EXISTS {STAGING}")
            cursor.execute(f"DROP TABLE IF EXISTS {contract.TABLE}")
    migrate(database)
