-- The landing table: transactions as they arrived, before anything cleaned
-- them. The source side of the streaming path, and the counterpart of
-- sql/schema.sql -- one row goes in here dirty and comes out of there clean.
--
-- Every source column is TEXT. That is not laziness, it is the same contract
-- src/spark/spark_setup.py enforces on the CSV reader and src/utils/io.py on
-- the workbook reader: the reader must not decide what "" or "5.727.580,00"
-- or "03-Jan-22" mean. A NUMERIC column here would coerce on the way in and
-- pre-empt the very coercion requirement 2 asks the pipeline to COUNT -- the
-- unparseable row would be rejected by the INSERT, before any stage could
-- mark it, and the cleaning report would be silent about a row that never
-- arrived. Typing happens once, on the way out, in src/db/contract.py.
--
-- The column names are the source's own, lowercased. Postgres folds unquoted
-- identifiers to lower case, and quoting twenty-two of them to keep the shout
-- would mean every hand-written query had to quote them too. src/db/raw.py
-- aliases them back to upper case on read, because that is the spelling every
-- cleaning stage looks for -- the same direction contract.py lowercases in.

CREATE TABLE IF NOT EXISTS raw_transactions (
    -- The event key. Numeric and generated, because what travels on Kafka is
    -- this id and nothing else: the message says "row 42 arrived", and the
    -- consumer goes and reads row 42. A natural key would not do -- txn_id is
    -- exactly the column the source gets wrong, and the duplicates stage
    -- exists because it repeats.
    --
    -- BY DEFAULT rather than ALWAYS, so a hand-written INSERT may state its
    -- own id when reproducing a specific row. The sequence does not learn
    -- about ids supplied that way; a later generated id can therefore collide
    -- with one inserted by hand. That is the standard identity-column caveat
    -- and the reason seed_raw.py lets the database allocate.
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The 22 source columns, in the order the extract's header states them,
    -- so a person reading this file and a person reading the CSV are looking
    -- at the same list. tests/test_db_raw.py asserts that they still are.
    user_id               TEXT,
    account_id            TEXT,
    txn_id                TEXT,
    txn_seq               TEXT,
    txn_date_time         TEXT,
    settle_date           TEXT,
    txn_amount            TEXT,
    txn_ccy               TEXT,
    billing_amount        TEXT,
    billing_currency      TEXT,
    fx_rate               TEXT,
    running_balance       TEXT,
    merchant_name         TEXT,
    mcc_code              TEXT,
    merchant_country      TEXT,
    merchant_city         TEXT,
    processing_code       TEXT,
    processing_type       TEXT,
    auth_code             TEXT,
    interest_rate_index   TEXT,
    inflation_index       TEXT,
    is_holiday_month      TEXT,

    -- Housekeeping ---------------------------------------------------------
    --
    -- Where the row came from. Free text rather than a foreign key: it is for
    -- a person asking "what is this" six weeks later, and the answer may be a
    -- file name, a hand-typed note, or nothing at all.
    source                TEXT,
    ingested_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- What the consumer has done with the row. NOT a work queue -- Kafka is
    -- the queue, and a consumer that polled this column instead would be a
    -- second, competing source of truth about what is outstanding. It is a
    -- record, so that a person can see at a glance which rows made it through
    -- and which failed, and so that FAILED rows can be re-emitted by id
    -- without guessing.
    status                TEXT NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CLEANED', 'FAILED')),
    -- When the consumer finished with it, either way. Distinct from
    -- cleaned_transactions.cleaned_at, which is the clean row's own timestamp:
    -- these two disagree by however long a redelivery took, and collapsing
    -- them would hide exactly that.
    processed_at          TIMESTAMPTZ,
    -- Why it failed, when it did. Truncated by the writer rather than by the
    -- column, so the message stays readable in a listing.
    last_error            TEXT
);

-- "What is still outstanding, and what blew up" is the only question this
-- table is queried by hand for.
CREATE INDEX IF NOT EXISTS idx_raw_status
    ON raw_transactions (status);
